backend:
  name: github
  repo: adamdjbrett/jcrt.org
  branch: main
  base_url: xxxx # yourworker cloudflare

media_folder: "public/img"

collections:
  - name: "home"
    label: "Home"
    preview: true
    files:
      - file: "content/index.md"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Hero Text", name: "text", widget: "text", hint: "The main text under the hero image."}
          - label: "Hero Button"
            name: "button"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - label: "Featured Section"
            name: "section"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string"}
              - {label: "Mode", name: "mode", widget: "string"}
          - label: "Blog Section"
            name: "blog"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}

  - name: "blogIndex"
    label: "Blog Index"
    preview: true
    files:
      - file: "content/blog.md"
        label: "Blog Listing Page"
        name: "blog_index"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "blog.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Pagination Settings"
            name: "pagination"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Data Source", name: "data", widget: "hidden", default: "collections.posts"}
              - {label: "Page Size", name: "size", widget: "number", value_type: "int", default: 6}
              - {label: "Reverse Order", name: "reverse", widget: "boolean", default: true}
          - label: "Test Data (Example)"
            name: "testdata"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Item", name: "item", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/blog/{% if pagination.pageNumber > 0 %}{{ pagination.pageNumber + 1 }}/{% endif %}index.html"}
          - {label: "Body Content (Optional)", name: "body", widget: "markdown", required: false}
  - name: "posts"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", hint: "A short summary of the post."}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", field: {label: "Tag", name: "tag", widget: "string"}}
      - label: "Author Key"
        name: "author"
        widget: "string"
        hint: "Authors"
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "authors_profile"
    label: "Author Profiles"
    folder: "content/authors"
    create: true
    identifier_field: "key"
    slug: "{{key}}"
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Full name of the author."}
      - {label: "Description", name: "description", widget: "string", hint: "Description of authors example University of Denver."}
      - {label: "Affiliation", name: "affiliation", widget: "string", hint: "Affiliation."}
      - {label: "Orcid", name: "orcid", widget: "string", hint: "Orcid."}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Profile Image", name: "image", widget: "image"}
      - label: "Social Links"
        name: "social"
        widget: "list"
        collapsed: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Icon (Font Awesome)", name: "icon", widget: "string", hint: "e.g., fa-solid fa-envelope"}
          - {label: "URL", name: "url", widget: "string"}
      - label: "Call-to-Action Button"
        name: "button"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
      - {label: "Biography", name: "body", widget: "markdown", hint: "The main content/bio of the author."}
  - name: "pages"
    label: "Static Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Permalink", name: "permalink", widget: "string", hint: "Example: /about/"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "archives"
    label: "Archives"
    folder: "content/archives"
    create: true
    path: "{{volume}}.{{issue}}/{{slug}}" 
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "archives.njk"}
      - {label: "Article Number", name: "article_number", widget: "string", hint: "Gunakan 01, 02, dst (Poin 7 Adam)"}
      - {label: "Volume", name: "volume", widget: "string", hint: "Contoh: 24"}
      - {label: "Issue", name: "issue", widget: "string", hint: "Contoh: 1"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author Name", name: "author", widget: "string", hint: "Nama lengkap penulis"}
      - {label: "Affiliation", name: "affiliation", widget: "string", required: false, hint: "Poin 8 Adam"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "PDF File", name: "pdf", widget: "file", required: false, hint: "Poin 5 Adam"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "metadata"
    label: "Metadata"
    preview: false
    files:
    - file: "_data/metadata.yaml"
      label: "Site Metadata"
      name: "site_metadata"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "text"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Language", name: "language", widget: "string"}
        - {label: "Locale", name: "locale", widget: "string"}
        - {label: "Favicon", name: "favicon", widget: "image"}
        - {label: "URL", name: "url", widget: "string"}
        - label: "Metasocial"
          name: "metasocial"
          widget: "list"
          fields:
            - {label: "Facebook", name: "facebook", widget: "string", required: false}
            - {label: "Twitter User", name: "twitteruser", widget: "string", required: false}
            - {label: "Twitter", name: "twitter", widget: "string", required: false}
        - label: "Navbar"
          name: "navbar"
          widget: "object"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Sub Title", name: "sub_title", widget: "string"}
            - label: "Social Links"
              name: "social"
              widget: "list"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Icon (Font Awesome)", name: "icon", widget: "string"}
                - {label: "URL", name: "url", widget: "string"}
        - label: "Sidebar"
          name: "sidebar"
          widget: "object"
          fields:
            - label: "Menu"
              name: "menu"
              widget: "object"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - label: "List Menu"
                  name: "list"
                  widget: "list"
                  fields:
                    - {label: "Nav Text", name: "nav", widget: "string"}
                    - {label: "URL", name: "url", widget: "string"}
            - label: "Info Section"
              name: "info"
              widget: "object"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - label: "List Items"
                  name: "list"
                  widget: "list"
                  fields:
                    - {label: "Image", name: "image", widget: "image"}
                    - {label: "Text", name: "text", widget: "text"}
                    - {label: "URL", name: "url", widget: "string"}
                - label: "Button"
                  name: "button"
                  widget: "object"
                  fields:
                    - {label: "Text", name: "text", widget: "string"}
                    - {label: "URL", name: "url", widget: "string"}
            - label: "Contact"
              name: "contact"
              widget: "object"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Text", name: "text", widget: "text"}
                - label: "Contact List"
                  name: "list"
                  widget: "list"
                  fields:
                    - {label: "Title", name: "title", widget: "string"}
                    - {label: "Icon (Font Awesome)", name: "icon", widget: "string"}
                    - {label: "URL", name: "url", widget: "string"}
        - label: "Footer"
          name: "footer"
          widget: "object"
          fields:
            - {label: "Text", name: "text", widget: "string"}
            
        - label: "Theory Dir"
          name: "site"
          widget: "object"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "text"}
            - {label: "URL", name: "url", widget: "string"}
            - {label: "Authors", name: "authors", widget: "string"}
            - {label: "Alert", name: "alert", widget: "markdown"}
        - {label: "Github User API Religious Theory", name: "github_user", widget: "string"}
        - {label: "Github Repo API Religious Theory", name: "github_repo", widget: "string"}
        - {label: "Github Branch API Religious Theory", name: "branch", widget: "string"}
